### ISSUE TITLE
Build 404 page 

### ISSUE THREAD

**Issue by jesscsommer** [jesscsommer/rjs-full-stack-project#92]
- [ ] Build client side
- [ ] Send users there when 404 from server (useHistory)

**Comment by rcblake** [comment]
Page not found, dear friend,
Lost in the vast digital void,
Haiku whispers fade.

Lost in cyberspace,
404 Haiku seeks solace,
A missing heartbeat.

Haiku realms vanish,
Error 404, soul weeps,
Silent poetry.

Infinite pixels,
404 Haiku's lament,
Lost in digital.

Error: not found.
Haiku's essence disappears,
Echoes fade away.

**Comment by rcblake** [comment]
I like the 1st on most but all are pretty good
